export const DummyProducts = [
  {
    id: 1,
    title: "Classic Monochrome Tees",
    rate: 4.5,
    reviews: 60,
    price: "55.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/cover.png",
  },
  {
    id: 2,
    title: "Monochromatic Wardrobe",
    rate: 3.2,
    reviews: 20,
    price: "25.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/cover1.png",
  },
  {
    id: 3,
    title: "Essential Neutrals",
    rate: 3.6,
    reviews: 25,
    price: "95.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/cover2.png",
  },
  {
    id: 4,
    title: "TURBANED Black",
    rate: 4.2,
    reviews: 54,
    price: "75.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/cover3.png",
  },
  {
    id: 5,
    title: "Elegant Ebony Sweatshirts",
    rate: 3.6,
    reviews: 25,
    price: "95.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/shirt.png",
  },
  {
    id: 6,
    title: "Sleek and Cozy Black",
    rate: 4.6,
    reviews: 49,
    price: "95.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/shirt2.png",
  },
  {
    id: 7,
    title: "Raw Black Tees",
    rate: 4.6,
    reviews: 23,
    price: "66.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/shirt3.png",
  },
  {
    id: 8,
    title: "MOCKUP Black",
    rate: 2.6,
    reviews: 25,
    price: "32.00",
    colors: ["blue", "yellow", "green"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    stock: 10,
    image: "/shirts/shirt4.png",
  },
];
